# Generated by Django 4.2.20 on 2025-03-06 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_attendance_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
    ]
